server:
  name: article-service
  bind_addr: 0.0.0.0:5030

redis:
  host: 127.0.0.1
  port: 6379
  password: aoliao123!!
  pool_size: 20

database:
  url: postgres://postgres:postgres@127.0.0.1:5432/blog_v2
  username: gragon
  password: aoliao123!!
  max_connections: 50
  min_connections: 10

snowflake:
  machine_id: 1
  node_id: 1

services:
  user_service_grpc: http://127.0.0.1:50051

logs:
  path: logs/article-service.log