[package]
name = "common-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
chrono.workspace = true
